# scripts/nfs-share.sh — worker reads EXL3 + slim Engram over NFSv4 on ConnectX.
# Sourced by start.sh. Same pattern as MiaAI-Lab/DeepSeek-v4.1-Flash-DGX-Sparks:
# workers do not copy the checkpoint. vLLM cpu_offload copies this rank's
# Engram heads into pinned RAM at load; decode does not mmap NFS.
#
# Reuses the live kernel nfsd (vllm-fn-nfs / glm53-nfs / dsv41-nfs /
# dsv41-exl3-nfs) — a second nfsd will not start. Publishes with hardlinks
# into ~/.cache/huggingface when that exporter is the HF cache.
#
# Expected docker volumes on the worker:
#   NFS_VOLUME_MODEL  device=:/dsv41-exl3     → /model
#   NFS_VOLUME_ENGRAM device=:/dsv41-engram   → /engram-src (shards 47+48 only)

NFS_IMAGE="${NFS_IMAGE:-dsv41-exl3-nfs:local}"
NFS_CONTAINER="${NFS_CONTAINER:-dsv41-exl3-nfs}"
NFS_VOLUME_MODEL="${NFS_VOLUME_MODEL:-dsv41-exl3-weights}"
NFS_VOLUME_ENGRAM="${NFS_VOLUME_ENGRAM:-dsv41-exl3-engram}"
NFS_EXPORT_MODEL="${NFS_EXPORT_MODEL:-dsv41-exl3}"
NFS_EXPORT_ENGRAM="${NFS_EXPORT_ENGRAM:-dsv41-engram}"
NFS_DOCKERFILE_DIR="${NFS_DOCKERFILE_DIR:-$SCRIPT_DIR/files/nfs-server}"
HF_EXPORT_ROOT="${HF_EXPORT_ROOT:-$HOME/.cache/huggingface}"
NFS_OPTS_CLIENT="${NFS_OPTS_CLIENT:-nfsvers=4.2,ro,nconnect=8,rsize=1048576,wsize=1048576,hard,timeo=600}"
NFS_SHARE="${NFS_SHARE:-1}"

# Export ACL. Defaults to the /24 the export is served on plus the worker's own
# address, because the worker may mount over a different link than it is reached
# on by ssh. Set NFS_CLIENTS in .env to pin it.
nfs_clients() {
    if [ -n "${NFS_CLIENTS:-}" ]; then
        echo "$NFS_CLIENTS"
        return 0
    fi
    local addr acl=""
    addr="$(nfs_server_ip)"
    case "$addr" in
        *.*.*.*) acl="${addr%.*}.0/24" ;;
    esac
    if [ -n "${WORKER_IP:-}" ] && [ "${WORKER_IP}" != "$addr" ]; then
        acl="${acl:+$acl,}${WORKER_IP}"
    fi
    echo "$acl"
}

nfs_server_ip() {
    local explicit="${NFS_SERVER_IP:-}"
    if [ -n "$explicit" ]; then
        printf '%s' "$explicit"
        return 0
    fi
    # The address the kernel picks to reach the worker is the one the worker can
    # mount from. Probe WORKER_IP first: on this kit 10.0.0.x are /32 loopback
    # aliases and the route goes out the CX7 link, which is exactly what we want
    # to export on. A src that lives on lo cannot serve anyone, so skip it.
    local peer src=""
    for peer in "${WORKER_IP:-}" "${ZFS_WORKER_IP:-}"; do
        [ -n "$peer" ] || continue
        src=$(ip route get "$peer" 2>/dev/null \
            | awk '{ for (i=1;i<=NF;i++) if ($i=="src") { print $(i+1); exit } }')
        case "$src" in ""|127.*) continue ;; esac
        ip -4 -o addr show dev lo 2>/dev/null | grep -qw "$src" && continue
        printf '%s' "$src"
        return 0
    done
    printf '%s' ""
}

nfs_live_container() {
    docker ps --format '{{.Names}}' \
        | grep -E '^(vllm-fn-nfs|glm53-nfs|dsv41-nfs|dsv41-exl3-nfs)$' \
        | head -1
}

nfs_rpc_ready() {
    local ip="$1"
    timeout 3 rpcinfo -t "$ip" nfs 4 >/dev/null 2>&1
}

nfs_write_exports() {
    local ctn="$1" clients="$2"
    docker exec -e NFS_CLIENTS="$clients" \
        -e NFS_OPTS="${NFS_OPTS:-ro,sync,no_subtree_check,no_root_squash,insecure,fsid=0}" \
        "$ctn" bash -lc '
      set -e
      {
        echo "# generated by dsv41-exl3-nfs (merged clients)"
        IFS="," read -ra addrs <<< "$NFS_CLIENTS"
        for addr in "${addrs[@]}"; do
          addr="${addr// /}"
          [ -z "$addr" ] && continue
          echo "/export ${addr}(${NFS_OPTS})"
        done
      } > /etc/exports
      exportfs -rav
    '
}

nfs_ensure_server() {
    local clients live
    clients="$(nfs_clients)"
    live="$(nfs_live_container || true)"

    if [ -n "$live" ] && nfs_rpc_ready 127.0.0.1; then
        log "NFS already up ($live) — keeping exporter, publishing EXL3+Engram into it"
        nfs_write_exports "$live" "$clients"
        NFS_REUSE_EXPORT=1
        NFS_LIVE_CTN="$live"
        return 0
    fi

    [ -d "$NFS_DOCKERFILE_DIR" ] || die "missing $NFS_DOCKERFILE_DIR"
    [ -d "$MODEL_HOST" ] || die "EXL3 checkpoint missing: $MODEL_HOST"
    [ -d "$ENGRAM_SRC" ] || die "slim Engram src missing: $ENGRAM_SRC (prepare_engram_src first)"

    log "building NFS image $NFS_IMAGE"
    docker build -q -t "$NFS_IMAGE" "$NFS_DOCKERFILE_DIR" >/dev/null
    docker rm -f "$NFS_CONTAINER" >/dev/null 2>&1 || true
    log "exporting EXL3 + slim Engram via NFS (clients: $clients)"
    # Export one real filesystem-backed bind mount. Exporting /export while
    # only its children are bind mounts leaves /export on overlayfs, which
    # kernel nfsd rejects with "does not support NFS export".
    docker run -d --name "$NFS_CONTAINER" --restart unless-stopped \
        --privileged --network host \
        -v "$HF_EXPORT_ROOT:/export:ro" \
        -e "NFS_CLIENTS=$clients" \
        "$NFS_IMAGE" >/dev/null
    local i
    for i in $(seq 1 20); do
        if nfs_rpc_ready 127.0.0.1; then
            log "NFS server ready ($NFS_CONTAINER)"
            NFS_REUSE_EXPORT=0
            NFS_LIVE_CTN="$NFS_CONTAINER"
            return 0
        fi
        sleep 0.5
    done
    docker logs "$NFS_CONTAINER" >&2 || true
    die "NFS server did not become ready. Check: docker logs $NFS_CONTAINER"
}

nfs_hardlink_tree() {
    local src="$1" dst="$2"
    mkdir -p "$dst"
    cp -a --link "$src"/. "$dst"/ 2>/dev/null || cp -al "$src"/. "$dst"/
}

nfs_publish() {
    local model_dst engram_dst n
    model_dst="${HF_EXPORT_ROOT}/${NFS_EXPORT_MODEL}"
    engram_dst="${HF_EXPORT_ROOT}/${NFS_EXPORT_ENGRAM}"
    mkdir -p "$model_dst" "$engram_dst"
    n=$(find "$model_dst" -maxdepth 1 -name 'model-*-of-*.safetensors' 2>/dev/null | wc -l | tr -d ' ')
    if [ "${n:-0}" -ge "$EXPECTED_SHARDS" ] && [ -f "$model_dst/config.json" ]; then
        log "NFS export already has ${NFS_EXPORT_MODEL} ($n shards)"
    else
        log "publishing EXL3 → $model_dst (hardlinks into the live NFS export)"
        nfs_hardlink_tree "$MODEL_HOST" "$model_dst"
        [ -f "$model_dst/config.json" ] || die "failed to publish EXL3 into $model_dst"
    fi
    if [ -f "$engram_dst/model-00047-of-00048.safetensors" ] \
       && [ -f "$engram_dst/model-00048-of-00048.safetensors" ] \
       && [ -f "$engram_dst/model.safetensors.index.json" ]; then
        log "NFS export already has ${NFS_EXPORT_ENGRAM} (shards 47+48)"
        if [ ! -f "$engram_dst/config.json" ] && [ -f "$ENGRAM_SRC/config.json" ]; then
            cp -a "$ENGRAM_SRC/config.json" "$engram_dst/config.json"
            log "copied config.json into ${NFS_EXPORT_ENGRAM}"
        fi
    else
        log "publishing slim Engram → $engram_dst (shards 47+48 only)"
        nfs_hardlink_tree "$ENGRAM_SRC" "$engram_dst"
        [ -f "$engram_dst/model-00047-of-00048.safetensors" ] \
            || die "failed to publish Engram into $engram_dst"
    fi
    NFS_DEVICE_MODEL=":/${NFS_EXPORT_MODEL}"
    NFS_DEVICE_ENGRAM=":/${NFS_EXPORT_ENGRAM}"
}

nfs_ensure_worker_volume() {
    local name="$1" device="$2"
    local addr
    addr="$(nfs_server_ip)"
    log "NFS volume $name on worker → nfs://${addr}${device}"
    worker_ssh "
    set -e
    docker volume rm '$name' >/dev/null 2>&1 || true
    docker volume create --driver local \
      --opt type=nfs \
      --opt o=addr=${addr},${NFS_OPTS_CLIENT} \
      --opt device=${device} \
      '$name' >/dev/null
  "
}

nfs_worker_has_file() {
    local volume="$1" rel="$2"
    worker_ssh "
    docker image inspect alpine:latest >/dev/null 2>&1 || docker pull alpine:latest >/dev/null
    docker run --rm -v '${volume}:/m:ro' alpine:latest test -f /m/${rel}
  " >/dev/null 2>&1
}

nfs_share() {
    [ "$NFS_SHARE" = "0" ] && die "NFS_SHARE=0 but weight backend is nfs"
    [ -n "$(nfs_server_ip)" ] || die "cannot work out which address to export EXL3 on: no route from this host to WORKER_IP=${WORKER_IP:-unset}. Set NFS_SERVER_IP (and NFS_CLIENTS) in .env."
    # Populate the filesystem-backed export before starting nfsd. The files
    # are hardlinks, so this consumes directory entries rather than another
    # ~387 GiB weight copy.
    nfs_publish
    nfs_ensure_server
    nfs_ensure_worker_volume "$NFS_VOLUME_MODEL" "${NFS_DEVICE_MODEL:-:/${NFS_EXPORT_MODEL}}"
    nfs_ensure_worker_volume "$NFS_VOLUME_ENGRAM" "${NFS_DEVICE_ENGRAM:-:/${NFS_EXPORT_ENGRAM}}"
    if nfs_worker_has_file "$NFS_VOLUME_MODEL" "config.json"; then
        log "worker $NFS_VOLUME_MODEL has config.json"
    else
        die "worker cannot see EXL3 over NFS ($NFS_VOLUME_MODEL). Check ACL (${NFS_CLIENTS:-10.0.22.0/24}) and docker logs of the nfs exporter."
    fi
    if nfs_worker_has_file "$NFS_VOLUME_ENGRAM" "model-00047-of-00048.safetensors"; then
        log "worker $NFS_VOLUME_ENGRAM has shard 47"
    else
        die "worker cannot see slim Engram over NFS ($NFS_VOLUME_ENGRAM)."
    fi
    WORKER_MODEL_BIND="$NFS_VOLUME_MODEL"
    WORKER_ENGRAM_BIND="$NFS_VOLUME_ENGRAM"
    export WORKER_MODEL_BIND WORKER_ENGRAM_BIND
    log "worker reads EXL3 + Engram 47+48 from spark1 over NFS (no local copy)"
}
